- name: create rabbitmq service
  k8s_v1_service:
    name: rabbitmq
    cluster_ip: "None"  # Currently broken for headless svc
    namespace: '{{ namespace }}'
    debug: yes
    labels:
      app: rabbitmq
      service: rabbitmq
    selector:
      app: rabbitmq
      service: rabbitmq
    ports:
      - port: 4369
        name: epmd
      - port: 5672
        name: amqp
      - port: 25672
        name: comm
  register: create-svc

- name: create rabbitmq management service
  k8s_v1_service:
    name: rabbitmq-mgmt
    namespace: '{{ namespace }}'
    labels:
      app: rabbitmq
      service: rabbitmq
    selector:
      app: rabbitmq
      service: rabbitmq
    ports:
      - name: rabbitmq-mgmt
        port: 15672

- name: Create rabbitmq configmaps
  ignore_errors: yes
  k8s_v1_config_map:
    name: rabbitmq
    namespace: '{{ namespace }}'
    state: present
    labels:
      service: rabbitmq
    data:
      config.json: |
        {
            "command": "/usr/sbin/rabbitmq-server",
            "config_files": [
                {
                    "source": "/var/lib/kolla/config_files/rabbitmq-env.conf",
                    "dest": "/etc/rabbitmq/rabbitmq-env.conf",
                    "owner": "rabbitmq",
                    "perm": "0600"
                },
                {
                    "source": "/var/lib/kolla/config_files/rabbitmq.config",
                    "dest": "/etc/rabbitmq/rabbitmq.config",
                    "owner": "rabbitmq",
                    "perm": "0600"
                }
            ],
            "permissions": [
                {
                    "path": "/var/lib/rabbitmq",
                    "owner": "rabbitmq:rabbitmq",
                    "recurse": true
                },
                {
                    "path": "/var/log/kolla/rabbitmq",
                    "owner": "rabbitmq:rabbitmq",
                    "recurse": true
                }
            ]
        }

      rabbitmq-env.conf: |
        NODE_IP_ADDRESS=
        NODE_PORT=
        RABBITMQ_SERVER_ERL_ARGS="+K true +P 1048576 -kernel inet_default_connect_options [{nodelay,true},{raw,6,18,<<15000:64/native>>}] -kernel inet_default_listen_options [{raw,6,18,<<15000:64/native>>}]"

      rabbitmq.config: |
        [
          {rabbit, [
            {tcp_listen_options, [
                 binary,
                 {packet,        raw},
                 {reuseaddr,     true},
                 {keepalive,     true},
                 {backlog,       128},
                 {nodelay,       true},
                 {linger,        {true, 0}},
                 {exit_on_close, false}
            ]},
            {tcp_listeners, [{"0.0.0.0", 5672}]},
            {cluster_partition_handling, pause_minority},
            {loopback_users, []},
            {queue_master_locator, <<"min-masters">>},
            {default_user, <<"guest">>},
            {default_pass, <<"rabbitpass">>}
          ]},
          {kernel, [
            {inet_dist_listen_max, 25672},
            {inet_dist_listen_min, 25672}
          ]}
        ].

- name: create rabbitmq statefulset
  k8s_v1beta1_stateful_set:
    name: rabbitmq
    namespace: '{{ namespace }}'
    state: present 
    spec_service_name: rabbitmq
    spec_template_metadata_name: rabbitmq
    replicas: '{{ replicas }}'
    service_account_name: openstack
    spec_template_metadata_labels:
      app: rabbitmq
      service: rabbitmq
    containers:
    - name: rabbitmq
      image: tripleoupstream/centos-binary-rabbitmq:latest
      env:
        - name: TZ
          value: UTC
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_KUBERNETES
          value: ""
      ports:
        - container_port: 5672
          name: rabbitmq
        - containerPort: 15672
          name: rabbitmq-mgmt
      volume_mounts:
        - name: kolla-config
          mountPath: /var/lib/kolla/config_files/
    volumes:
      - name: kolla-config
        config_map:
          name: rabbitmq

